name: rabbito
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  avatar_glow:
  custom_navigation_bar: ^0.8.2
  flutter_onboard: ^1.0.3
  google_fonts: ^2.1.0
  get: ^4.3.8
  flutter_localizations:
    sdk: flutter
  expandable: ^5.0.1
  shared_preferences: ^2.0.7
  flutter_secure_storage: ^4.2.1
  email_validator: ^2.0.1
  flutter_awesome_buttons: ^1.1.0
  liquid_progress_indicator: ^0.4.0
  flutter_fortune_wheel: ^1.1.0
  loading_indicator: ^3.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/appbar/coin.png
    - assets/images/appbar/cup.png
    - assets/images/appbar/heart.png
    - assets/images/appbar/star.png
    - assets/images/appbar/flag.png
    - assets/images/logo.png
    - assets/images/navigation/shop.png
    - assets/images/navigation/user.png
    - assets/images/navigation/game.png
    - assets/images/navigation/ranking.png
    - assets/images/introduction/welcome1.png
    - assets/images/introduction/welcome2.png
    - assets/images/introduction/welcome3.png
    - assets/images/introduction/welcome4.png
    - assets/images/leagues/gem.png
    - assets/images/leagues/diamond.png
    - assets/images/leagues/platinum.png
    - assets/images/leagues/gold.png
    - assets/images/leagues/silver.png
    - assets/images/leagues/bronze.png
    - assets/images/leagues/copper.png
    - assets/images/leagues/iron.png
    - assets/images/ranking/progress.png
    - assets/images/ranking/carrot1.png
    - assets/images/ranking/carrot2.png
    - assets/images/ranking/badge.png
    - assets/images/ranking/clock.png
    - assets/images/game-home/chest1.png
    - assets/images/game-home/chest2.png
    - assets/images/game-home/roulette.png
    - assets/images/game-home/settings.png
    - assets/images/game-home/carrot1.png
    - assets/images/game-home/carrot2.png
    - assets/images/game-home/donation.png
    - assets/images/game-home/sound1.png
    - assets/images/game-home/sound2.png
    - assets/images/game-home/sound3.png
    - assets/images/game-home/music1.png
    - assets/images/game-home/music2.png
    - assets/images/game-home/share1.png
    - assets/images/game-home/share2.png
    - assets/images/game-home/close1.png
    - assets/images/game-home/close2.png
    - assets/images/profile/book.png
    - assets/images/profile/gift.png
    - assets/images/profile/man.png
    - assets/images/profile/woman.png
    - assets/images/profile/achievement.png
    - assets/images/widgets/ticket1.png
    - assets/images/widgets/ticket2.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
